# Gradle JVM 内存与守护进程
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# 项目路径含中文（"彩记"），AGP 警告可忽略
android.overridePathCheck=true

# 强制使用 Android Studio 自带 JBR 21，避免与系统 JDK 25 冲突
org.gradle.java.home=D:/andriod_studio/jbr

